# Generated by Django 4.0.2 on 2022-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(max_length=30, verbose_name='lot_type')),
                ('phase', models.CharField(max_length=30, verbose_name='phase')),
                ('block', models.CharField(max_length=30, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, verbose_name='lot_no.')),
                ('terms', models.CharField(max_length=30, verbose_name='termsofpayment')),
                ('fullname', models.CharField(max_length=99, verbose_name='fullname')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=30, verbose_name='gender')),
                ('contacts', models.IntegerField(verbose_name='contacts')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('email', models.EmailField(max_length=99, verbose_name='email')),
            ],
        ),
    ]
