# Generated by Django 4.0.2 on 2022-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0002_inquiryform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryform',
            name='lot_type',
            field=models.CharField(choices=[('Lawn Lot', 'Lawn Lot'), ('Mausoleum', 'Mausoleum'), ('Niche', 'Niche'), ('Apartment Type', 'Apartment Type')], max_length=30, verbose_name='lot_type'),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=30, verbose_name='termsofpayment'),
        ),
    ]
