# Generated by Django 4.0.2 on 2022-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0003_alter_inquiryform_lot_type_alter_inquiryform_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryform',
            name='address',
            field=models.CharField(max_length=99, verbose_name='address'),
        ),
    ]
