# Generated by Django 4.0.2 on 2022-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0004_alter_inquiryform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryform',
            name='contacts',
            field=models.CharField(max_length=11, verbose_name='contacts'),
        ),
    ]
