# Generated by Django 4.0.2 on 2022-10-31 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0005_alter_inquiryform_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormModel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id')),
                ('date', models.DateField(verbose_name='date')),
                ('phase', models.CharField(max_length=30, verbose_name='phase')),
                ('block', models.CharField(max_length=30, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, verbose_name='lot_no.')),
                ('fullname', models.CharField(max_length=99, verbose_name='fullname')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=30, verbose_name='gender')),
                ('contacts', models.CharField(max_length=11, verbose_name='contacts')),
                ('address', models.CharField(max_length=99, verbose_name='address')),
                ('email', models.EmailField(max_length=99, verbose_name='email')),
            ],
        ),
        migrations.RenameModel(
            old_name='InquiryForm',
            new_name='InquiryFormModel',
        ),
    ]
