# Generated by Django 4.0.2 on 2022-10-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0006_applicationformmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id'),
        ),
    ]
