# Generated by Django 4.0.2 on 2022-11-01 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0009_alter_applicationformmodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyersFormModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id')),
                ('lot_type', models.CharField(choices=[('Lawn Lot', 'Lawn Lot'), ('Mausoleum', 'Mausoleum'), ('Niche', 'Niche')], max_length=30, null=True, verbose_name='lot_type')),
                ('phase', models.CharField(max_length=30, null=True, verbose_name='phase')),
                ('block', models.CharField(max_length=30, null=True, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, null=True, verbose_name='lot_no.')),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=30, null=True, verbose_name='termsofpayment')),
                ('fullname', models.CharField(max_length=99, null=True, verbose_name='fullname')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('gender', models.CharField(max_length=30, null=True, verbose_name='gender')),
                ('contacts', models.CharField(max_length=11, null=True, verbose_name='contacts')),
                ('address', models.CharField(max_length=99, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=99, null=True, unique=True, verbose_name='email')),
            ],
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='email',
            field=models.EmailField(max_length=99, null=True, unique=True, verbose_name='email'),
        ),
    ]
