# Generated by Django 4.0.2 on 2022-11-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0012_product_lotorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='product',
            name='terms',
        ),
        migrations.AddField(
            model_name='lotorder',
            name='balance',
            field=models.FloatField(null=True, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='lotorder',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='lotorder',
            name='pay',
            field=models.FloatField(null=True, verbose_name='pay'),
        ),
        migrations.AddField(
            model_name='lotorder',
            name='terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=50, null=True, verbose_name='terms'),
        ),
    ]
