# Generated by Django 4.0.2 on 2022-11-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0013_remove_product_due_date_remove_product_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
