# Generated by Django 4.0.2 on 2022-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0014_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotorder',
            name='paid_date',
            field=models.DateTimeField(null=True, verbose_name='paid date'),
        ),
    ]
