# Generated by Django 4.0.2 on 2022-11-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0015_lotorder_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=99, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(max_length=11, null=True, verbose_name='contacts'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=30, null=True, verbose_name='gender'),
        ),
    ]
