# Generated by Django 4.0.2 on 2022-11-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0017_alter_lotorder_due_date_alter_lotorder_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='born.'),
        ),
        migrations.AddField(
            model_name='product',
            name='deceased',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='deceased.'),
        ),
        migrations.AddField(
            model_name='product',
            name='died',
            field=models.DateField(blank=True, null=True, verbose_name='died.'),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.CharField(max_length=200, null=True, verbose_name='latitude.'),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.CharField(max_length=200, null=True, verbose_name='longitude.'),
        ),
    ]
