# Generated by Django 4.0.2 on 2022-11-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0019_alter_product_born_alter_product_deceased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='born',
            field=models.DateField(blank=True, default='None', null=True, verbose_name='born.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deceased',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='deceased.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='died',
            field=models.DateField(blank=True, default='None', null=True, verbose_name='died.'),
        ),
    ]
