# Generated by Django 4.0.2 on 2022-11-30 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0021_alter_product_born_alter_product_deceased_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=50, null=True, verbose_name='terms')),
                ('pay', models.FloatField(null=True, verbose_name='pay')),
                ('balance', models.FloatField(null=True, verbose_name='balance')),
                ('paid_date', models.DateField(null=True, verbose_name='paid date')),
                ('status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid')], max_length=200, null=True, verbose_name='status')),
                ('due_date', models.DateField(null=True, verbose_name='due date')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='THESISAPP.product', verbose_name='product')),
            ],
        ),
    ]
