# Generated by Django 4.0.2 on 2022-12-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0025_alter_lotorder_balance_alter_lotorder_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender'),
        ),
    ]
