# Generated by Django 4.0.2 on 2022-12-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0026_remove_user_age_user_birth_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='buyersformmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='inquiryformmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
        migrations.AddField(
            model_name='buyersformmodel',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
        migrations.AddField(
            model_name='inquiryformmodel',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='buyersformmodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='inquiryformmodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender'),
        ),
    ]
