# Generated by Django 4.0.2 on 2022-12-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0027_remove_applicationformmodel_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotorder',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
