# Generated by Django 4.0.2 on 2022-12-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0028_remove_lotorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='THESISAPP.product', verbose_name='product'),
        ),
    ]
