# Generated by Django 4.0.2 on 2022-12-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0029_alter_lotorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='born',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deceased',
        ),
        migrations.RemoveField(
            model_name='product',
            name='died',
        ),
        migrations.CreateModel(
            name='Deads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='deceased.')),
                ('born', models.DateField(blank=True, default=None, null=True, verbose_name='born.')),
                ('died', models.DateField(blank=True, default=None, null=True, verbose_name='died.')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='THESISAPP.product', verbose_name='lot')),
            ],
        ),
    ]
