# Generated by Django 4.0.2 on 2022-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0030_remove_product_born_remove_product_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clerk1',
            field=models.BooleanField(default=False, verbose_name='Is clerk1'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_clerk2',
            field=models.BooleanField(default=False, verbose_name='Is clerk2'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_clerk3',
            field=models.BooleanField(default=False, verbose_name='Is clerk3'),
        ),
    ]
