# Generated by Django 4.0.2 on 2022-12-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0031_user_is_clerk1_user_is_clerk2_user_is_clerk3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deads',
            name='lot',
        ),
        migrations.AddField(
            model_name='deads',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='THESISAPP.lotorder', verbose_name='owner'),
        ),
    ]
