# Generated by Django 4.0.2 on 2022-12-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0032_remove_deads_lot_deads_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotorder',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='THESISAPP.product', verbose_name='product'),
        ),
    ]
